### ISSUE TITLE
ImportError: cannot import name 'gen_config_yaml_raw' from 'examples.speech_to_text.data_utils'

### ISSUE THREAD

**Issue by lingxiaoxue** [dqqcasia/mosst#1]
## 🐛 Bug
execute script： python3 ./examples/speech_to_text/prep_mustc_data_raw.py --data-root ${MUSTC_ROOT}   --tgt-lang ${LANG}
Could not find function gen_config_yaml_raw：
![image](https://user-images.githubusercontent.com/15962990/176082691-679ecd90-37e8-4bc1-8db0-8e8647f2796a.png)

The configuration file config_raw.yaml could not be found in the project code：
![image](https://user-images.githubusercontent.com/15962990/176082855-07aa73f5-a49f-4900-9e6d-c404f3af4bab.png)

**Comment by dqqcasia** [comment]
solved.
