### ISSUE TITLE
How to convert the offline models to support streaming translation task?

### ISSUE THREAD

**Issue by lingxiaoxue** [dqqcasia/mosst#2]
## ❓ Questions and Help

I am hoping to ask you a few questions：
 1.the model I trained and fine-tuned following the steps from the must-c en-de is the  offline model ?
 2.How to convert the offline models to support streaming translation task?
 3. What's the difference of the online and offline model?
 
![image](https://user-images.githubusercontent.com/15962990/176402650-415560a4-a99f-47c7-ad4e-3f0dda1b7a30.png)

**Comment by dqqcasia** [comment]
Sorry for the late reply. Thanks for your attention. 

In our work, the model can both serve for online translation and offline translation. "converting the offline models to support streaming translation task" is aimed to be compatible with Fairseq and SimulEval for online evaluation, which doesn't need more training or finetuning. 

Maybe you can concat me at 
dongqianqian@bytedance.com, and we can communicate directly with WeChat.
